version: '3'

services:
  mainnet:
    container_name: mainnet
    image: ton-node-mainnet
    volumes:
      - /data:/var/ton-work/db
      - ./config:/var/ton-work/network
    ports:
      - 30001:30001
      - 30002:30002
      - 30003:30003
      - 30004:30004
    environment:
      - VERBOSE=3
      - CONFIG=https://raw.githubusercontent.com/ton-blockchain/ton-blockchain.github.io/main/global.config.json
      - LITESERVER=true
      - CONSOLE_PORT=30001
      - PUBLIC_PORT=30002
      - LITESERVER_PORT=30003

  toncenter:
    container_name: http-toncenter
    image: ton-toncenter-mainnet
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./config:/var/ton-work/network
    environment:
      - CONFIG=https://ton-blockchain.github.io/global.config.json
      - PUBLIC_PORT=8082
    env_file:
      - 'toncenter.env'
    depends_on:
      - "mainnet"
